export const CREATE_SHELF_REQUEST = "CREATE_SHELF_REQUEST";
export const CREATE_SHELF_SUCCESS = "CREATE_SHELF_SUCCESS";
export const CREATE_SHELF_RESET = "CREATE_SHELF_RESET";
export const CREATE_SHELF_ERROR = "CREATE_SHELF_ERROR";

export const GET_SHELVES_REQUEST = "GET_SHELVES_REQUEST";
export const GET_SHELVES_SUCCESS = "GET_SHELVES_SUCCESS";
export const GET_SHELVES_RESET = "GET_SHELVES_RESET";
export const GET_SHELVES_ERROR = "GET_SHELVES_ERROR";

export const DELETE_SHELF_REQUEST = "DELETE_SHELF_REQUEST";
export const DELETE_SHELF_SUCCESS = "DELETE_SHELF_SUCCESS";
export const DELETE_SHELF_RESET = "DELETE_SHELF_RESET";
export const DELETE_SHELF_ERROR = "DELETE_SHELF_ERROR";
