export const CREATE_SHELF_REQUEST = "CREATE_SHELF_REQUEST";
export const CREATE_SHELF_SUCCESS = "CREATE_SHELF_SUCCESS";
export const CREATE_SHELF_RESET = "CREATE_SHELF_RESET";
export const CREATE_SHELF_ERROR = "CREATE_SHELF_ERROR";
