export const CREATE_USER_REQUEST = "CREATE_USER_REQUEST";
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";
export const CREATE_USER_RESET = "CREATE_USER_RESET";
export const CREATE_USER_ERROR = "CREATE_USER_ERROR";
export const CREATE_USER_CLEAR_ERROR = "CREATE_USER_CLEAR_ERROR";
